version: 2
jobs:
  android:
    working_directory: ~/qwallet
    docker:
      - image: circleci/android:api-28-node8-alpha

    steps:
      - checkout:
          path: ~/qwallet
      - attach_workspace:
          at: ~/qwallet

      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4" > ~/.ruby-version
      - run:
          name: Install NPM packages
          command: npm i
      - run: sh .circleci/download.sh
      - run: mkdir -p ~/.gradle && cp gradle.properties ~/.gradle && cp qwallet-android.keystore ./android/app
      - run: gem install fastlane -NV
      - run: fastlane android beta

      - persist_to_workspace:
          root: ~/qwallet
          paths:
            - node_modules

workflows:
  version: 2
  react-native:
    jobs:
      - android:
          filters:
            branches:
              only:
                - staging
